export type FormData = {
  firstName: string;
  lastName: string;
  email: string;
  password: string;
  phoneNumber?: string;
  dateOfBirth?: Date ;
  gender: string;
  maritalStatus?: string;
  religion?: string;
  highestDegree?: string;
  languages?: string | string[];
  technicalSkills?: string | string[];
  softSkills?: string | string[];
  companyName: string;
  companyaddress: string;
  companydescription: string;
  institutionName: string;
  graduationYear: number;
  fieldOfStudy: string;
  bio: string;
  role: string;
  startDate: Date;
  endDate?: Date;
  isCurrent: boolean;
  facebook?: string;
  twitter?: string;
  linkedin?: string;
  instagram?: string;
};
