export { default as ProfileTabs } from "./ProfielTabs/ProfielTabs";
export { default as AccountInformation } from "./AccountInformation/AccountInformation";
export { default as PersonalInformation } from "./PersonalInformation/PersonalInformation";
export { default as IndividualAnalytics } from "./IndividualAnalytics/IndividualAnalytics";
export { default as AnalyticsChart } from "./AnalyticsChart/AnalyticsChart";
export { default as AmountOfContentAddedUser } from "./AmountOfContentAddedUser/AmountOfContentAddedUser";
export { default as UserProfileDetail } from "./UserProfileDetail/UserProfileDetail";
export { default as TitleRow } from "./TitleRow/TitleRow";
export { default as CustomPersonalDetailCard } from "./CustomPersonalDetailCard/CustomPersonalDetailCard";
